name: 'ECS Deploy'
description: 'Deploys single container to ecs with environment variables'
inputs:
  image:
    description: 'Container image'
    required: true
  environment:
    description: 'Deploy environment name'
    required: true
  service:
    description: 'Service name'
    required: true
  cluster:
    description: 'ECS cluster'
    required: true
  variables:
    description: 'List of environment variables'
    required: false


runs:
  using: "composite"
  steps:
    - name: Get current task definition
        run: |
          aws ecs describe-task-definition --task-definition  ${{ inputs.environment }}-${{ inputs.service }} --query taskDefinition > task-definition.json

    - name: Update task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ inputs.service }}
          image:  ${{ inputs.image }}
          environment-variables: ${{ inputs.variables }}

    - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ inputs.environment }}-${{ inputs.service }}-service
          cluster: ${{ inputs.cluster }}
          wait-for-service-stability: true